name = "mapeamento-radio-2"
compatibility_date = "2024-01-01"
pages_build_output_dir = "./"

# Configuração para Cloudflare Pages
[env.production]
name = "mapeamento-radio-2"

# Variáveis de ambiente (configure no dashboard)
[env.production.vars]
# NOTION_TOKEN será configurado via dashboard do Cloudflare
# No dashboard: Settings > Environment Variables > Production
# Adicione: NOTION_TOKEN = seu_token_aqui
